name: BuildAndTest

on: [push]

jobs:
  build:

    runs-on: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
    - uses: actions/checkout@v1
    - name: Build with dotnet
      working-directory: ./src
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ./src
      run: dotnet test
