name: BuildAndTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
      # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 3.1
    - uses: actions/checkout@v1
    - name: Build with dotnet
      working-directory: ./src
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ./src
      run: dotnet test
